### ISSUE TITLE
Why do we hash the CSRF?

### ISSUE THREAD

**Issue by D1plo1d** [pillarjs/csrf#11]
I was looking through the code to understand the security model and noticed that the CSRF is being hashed with SHA-1. There's a lot of talk about replacing SHA-1 with harder to break hashing function (eg. SHA-256) in other areas so it worried me at first to see SHA-1 used to protect CSRFs. But then I got to thinking about it more... why are we hashing the CSRF? AFAIK the CSRF (even in plaintext) is not enough for a malicious agent to generate the cookie that they would need to steal a session.

What threat does hashing the CSRF token secure against as opposed to storing the CSRF in plain text in both the browser javascript and the cookie? And if the hashing is important to security of CSRFs should we be migrating CSRF to SHA-256?

**Comment by dougwilson** [comment]
All the hashing does is take the secret + the randomness to generate a single key. The reason this is done is for attacks where sending the exact same page content over and over can be guessed, so you want the content of your page to vary with every request. This is just a mechanism to generate many tokens that correspond to a single secret.

We can change it, but would rather understand the purpose of the change and what the real attack vectors are, but the SHA1 is not being used to actually secure anything here, as the security is generated through the use of the random bytes of the secret.

> There's a lot of talk about replacing SHA-1 with harder to break hashing function 

Can you elaborate on what these talks are? What makes one hash harder to break than another? How long does it take to break the SHA1? Is it longer than your user session? If an attacker does not actually know the salt or secret (which is the security model of CSRF tokens--that the attacker cannot see the page source), does our use of SHA1 diminish the search space of simply iterating through all possible SHA1s?

**Comment by D1plo1d** [comment]
> The reason this is done is for attacks where sending the exact same page content over and over can be guessed, so you want the content of your page to vary with every request.

Ok, I think I understand. Eg. the user posts a form and hits the submit button multiple times or the browser history is used for a replay attack somehow?

I'm reading through the source of csurf as an example csrf integration though and I'm still not sure I understand how that is implemented. Sorry, this is probably a super basic question but I think key to me understanding how you are using SHA-1: how does the server prevent replays of old CSRF tokens? Is the CSRF token also stored in the session? Does the secret change with each request that changes the state? Basically how are old CSRF tokens invalidated in csurf + csrf?

> What makes one hash harder to break than another

The question of what makes one hash harder to break then another is one that I do not feel qualified to definitively answer. The potential threats to SHA1 seems largely hypothetical at the moment however they have been deemed disconcerting enough that other areas such as HTTPS certs have already moved to SHA256 based on these hypothetical concerns. Here are some sources:

* https://blog.qualys.com/ssllabs/2014/09/09/sha1-deprecation-what-you-need-to-know
* http://security.stackexchange.com/a/19712/67032
* http://arstechnica.com/security/2012/10/sha1-crypto-algorithm-could-fall-by-2018/

**Comment by dougwilson** [comment]
> Ok, I think I understand. Eg. the user posts a form and hits the submit button multiple times or the browser history is used for a replay attack somehow?

No.

> how does the server prevent replays of old CSRF tokens?

We don't.

> Is the CSRF token also stored in the session?

No.

> Does the secret change with each request that changes the state?

No.

> Basically how are old CSRF tokens invalidated in csurf + csrf?

They are not, because that is not part of how CSRF tokens really work. For one, it would badly break users having multiple tabs/windows to your web site.
