### ISSUE TITLE
I don't understand the purpose of the library - it does not implement CSRF protection

### ISSUE THREAD

**Issue by ntaranov** [pillarjs/csrf#18]
I, as an attacker, go the the form I'm interested in and receive the CSRF token. Then I save it and use it with a malicious CSRF request later. 

As "verify" only checks tokens based on a random taken from the token itself and the sever secret, that remains the same, the token will be always valid. Instead, "verify" should check the token against something that changes from request to request or from session to session either stored on the server or in a cookie.

https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#token-based-mitigation

**Comment by ctcpip** [comment]
I think your confusion comes from the fact that this package is NOT middleware; it's only a module for generating the tokens.  Per the readme: "Use this module to create custom CSRF middleware."

CSRF middleware would use this module as part of a complete implementation, which, as you pointed out, would be checking the CSRF token matches against the token stored as part of the user's session or cookie.  You can see this for example in the (now-deprecated) [csurf package](https://github.com/expressjs/csurf/blob/f4fa792167c2bc5ec3576cc8c4f2776df2336271/index.js#L221) that consumed this module.

**Comment by ntaranov** [comment]
I don't think I'm confused. In fact, I tried to follow this way of thinking and didn't find any benefit of using this package versus just storing hmac(value1, secret)  in the token and just value1 in the cookie. So, as I understand it, if the package is intended to be used standalone - it's not secure, if it's intended to be used as a part of middleware - it's not very useful (pretty much useless). 

Of course, I'll happily see any valid point and change my understanding, if there is a solid argument.

**Comment by ctcpip** [comment]
It is definitely not intended to be used standalone.  Express and its ecosystem are very modular; sometimes it may seem odd that certain components have their own dedicated module, such as this one.  Whether you find the module useful or not is up to you; I don't have a position on the matter.  I am clarifying that the module is not standalone CSRF middleware and the readme should make that clear.  If that's not clear enough, we should look to improving it.

**Comment by ntaranov** [comment]
Thanks for answering and for confirming that the module is not intended to be used stand-alone. My point was that if it's intended to be used inside a middleware, then such middleware can be easier  implemented without the module code-wise as compared to using it. Additionally, I would argue that the ability to figure out both hashed token and hash from the token itself can lead users to conclusion that the module in fact can be used stand-alone. Even though this is clearly a speculation, my own experience tells me that this definitely can happen, has happened and in production in multiple application right now. Thus, I conclude that the value the module bring is actually negative. This is the reason behind my "I don't understand the purpose" wording in the original header.
