### ISSUE TITLE
Attaching domain to token

### ISSUE THREAD

**Issue by thetutlage** [pillarjs/csrf#7]
Don't you think, one should attach a domain to token creation, which means if token is received from a different domain it will be discarded. 

## Example

```
tokens.create(secret, domain)
tokens.verify(secret, token, domain)
```

## Here's why

First i agree, it is not this module problem to deal with sessions or cookies. But as a general approach i will do following with this module.

1. Create a token and set it under input field.
2. Save secret under session or cookie.
3. Check token with session using verify method.

Now the problem is, anyone can quickly grab this token by visiting a webpage on my website. Also they can copy the session from the network tab.

After this all one need to do is make CURL request by setting above values and VOILA csrf has been compromised.

**Comment by dougwilson** [comment]
> Now the problem is, anyone can quickly grab this token by visiting a webpage on my website. Also they can copy the session from the network tab.

This is not what CSRF is, so this module does not protect against that. You may want to read up on OWASP or another source on what CSRF is and how the protections work for preventing it.

A user can always make requests from any program against their own session, as that has nothing to do with CSRF, which is a browser-based non-user-interactive escalation of privileges.
